main: me.herobrinedobem.heventos.HEventos
name: CovilHEventos
version: 1.6.5
author: Espc7
description: Plugin de eventos automaticos
api-version: 1.18

commands:
    evento:
        description: Todos os comandos do plugin